### ISSUE TITLE
Master password text field not masked

### ISSUE THREAD

**Issue by patelhiren** [OpenSesameManager/OpenSesame#14]
Testing on an iPad Pro running iOS 15, on first launch when prompted to enter a new master password, the password field is not properly masked as a password and shows the full text entry.

**Comment by rainloreley** [comment]
I opened a PR for this issue, this should fix it: #12

**Comment by EthanLipnik** [comment]
https://github.com/OpenSesameManager/OpenSesame/pull/12#issuecomment-904905624

**Comment by EthanLipnik** [comment]
[Fix](https://github.com/OpenSesameManager/OpenSesame/commit/1007eb139592f8a840e3a93799849ba41035f86c)
