### ISSUE TITLE
Feature Request: Account names

### ISSUE THREAD

**Issue by rainloreley** [OpenSesameManager/OpenSesame#15]
## Idea
Account names for saved logins

## Why?
Sometimes a login doesn't have to have a website associated with it (e.g. computer logins, database credentials,...). Adding a account name field would

1. remove the need to for a website url
2. enable users to differentiate between multiple accounts on the same platform without needing to look at the username (e.g. Twitter) (even more helpful if the username is the same which can be the case for Microsoft accounts)

**Comment by EthanLipnik** [comment]
Great idea! Current issue with changing something as big with that is CoreData + CloudKit having a lot of migration issues. Once I figure that out, I can work on migrating domains to general account names
