### ISSUE TITLE
Question: Are Remote Notifications needed for CloudKit?

### ISSUE THREAD

**Issue by feralbob** [OpenSesameManager/OpenSesame#20]
I noticed that the AppDelegates for both iOS/macOS - perform a call to registerForRemoteNotifications - yet neither has appropriate calls to get the DeviceToken e.g. application(_:didRegisterForRemoteNotificationsWithDeviceToken:) or to handle the error.

https://www.hackingwithswift.com/read/33/8/delivering-notifications-with-cloudkit-push-messages-ckquerysubscription suggests that the DeviceToken is silently made available to CK

> If there was no error, we call registerForRemoteNotifications(), which creates a unique device token that can be used to message this device. That device token is silently handed off to CloudKit, so we don’t need to do anything other than request it.

I haven't seen in the app where CloudKit is using those notifications - so the probably naive question is...

Is the call to registerForRemoteNotifications needed for CloudKit integration or are both AppDelegates not needed? (and could the RemoteNotification entitlement be removed too?)

**Comment by EthanLipnik** [comment]
It used notifications when the database used Realm but I suppose it doesn't since we're now using CoreData

**Comment by EthanLipnik** [comment]
The entitlement is required but I removed AppDelegate. The original PR had merge conflicts so I had to do it myself
