### ISSUE TITLE
No option to dismiss "Forgot your password?" alert on lock screen

### ISSUE THREAD

**Issue by rainloreley** [OpenSesameManager/OpenSesame#22]
**Bug description**
When clicking the little "i" at the top right on the lock screen view, it shows an alert with an option to reset the password, but there's no way for the user to cancel the operation other than relaunching the app.

**To Reproduce**
1. Open the app (or click the lock icon when already in the app)
2. Click the "i" icon at the top

**Expected behavior**
There should be an option to dismiss the alert and to not reset the password. I clicked on it because I was curious what it is. Maybe the "Reset password" option should also have the `descructive` attribute to make it red.
Is there a backup of the data stored when resetting the password? Because currently it's a bit easy to reset it and delete all data which is really bad when you store all logins within the app.

**Screenshots**
![17AFA7D7-0D48-4D34-BF0B-8973B02EE001](https://user-images.githubusercontent.com/28984823/131476668-52d36552-b3fb-46af-ae28-fb4cd2b50f35.png)

**Device**
 - Device: iPad Air 4th generation
 - OS: iOS 15.0 Beta (19A5337a)
 - App Version 1.0 Build 8

**Comment by EthanLipnik** [comment]
[Fix](https://github.com/OpenSesameManager/OpenSesame/commit/e9d4645f0d361d14e853a98aa3cd513eefb2e3ab)
