### ISSUE TITLE
AES-GCM Nonce reuse

### ISSUE THREAD

**Issue by tspop** [OpenSesameManager/OpenSesame#6]
From what I can tell nonces are saved to the keychain and reused [here](https://github.com/OpenSesameManager/OpenSesame/blob/0751d063d45a37eaf4a753f82747773c644fc451/Shared/Services/CryptoSecurityService.swift#L19). 

[Nonces should never be re-used](https://crypto.stackexchange.com/questions/26790/how-bad-it-is-using-the-same-iv-twice-with-aes-gcm)

**Comment by EthanLipnik** [comment]
New release tomorrow that will fix this. Just gotta add a migration block.
