### ISSUE TITLE
Users can set the master password to blank which essentially locks out the app for anything but FaceID

### ISSUE THREAD

**Issue by jawshoeadan** [OpenSesameManager/OpenSesame#8]
On my first app open, I just hit enter in the master password, and I’m unable to change it. Also, I don’t think users should be able to do this. 

Edit: forgot to mention that the reason it locks out the master password box is because it lets you set the password to blank, but on reopen, it doesn’t let you enter blank text in the master unlock page. How can I change the password after?

**Comment by EthanLipnik** [comment]
Hi! Next version will fix this and allow you to reset the password
